### ISSUE TITLE
Docker compose fails for TH 3.4,  ES 6.8, CTX 3.0

### ISSUE THREAD

**Issue by mnmnc** [TheHive-Project/TheHive#1007]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (client)       | Fedora
| TheHive version / git hash   | 3.4.0-RC1
| Package Type              |  Docker

### Problem Description
`docker-compose up` fails with ElasticSearch exiting with code 1. 

### Steps to Reproduce
1. Use docker compose yaml
```
version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - script.inline=true
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  cortex:
    image: thehiveproject/cortex:3.0.0-RC3
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
  thehive:
    image: thehiveproject/thehive:3.4.0-RC1
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
```
1. watch it fails with ES quitting: `thehive-docker_elasticsearch_1 exited with code 1`
1. Check logs at: https://gist.githubusercontent.com/mnmnc/d79e730c6685dd5900cdcd59be906eb3/raw/99749f4293c04cf8b67a7420e5b2a69661d9611f/docker%2520compose%2520fail%2520log
