### ISSUE TITLE
Docker-Compose ElasticSearch incompatibility

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/TheHive#1140]
# Docker-Compose ElasticSearch incompatibility

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | N/A (Only local testing)
| OS version (client)       | OSX
| TheHive version / git hash   | c44df9d83e734377ab526f75014046f79a9f2a0f (latest master at time of writing)
| Package Type              | Docker (docker-compose)
| Browser type & version    | If applicable

### Problem Description
The [docker compose](https://github.com/TheHive-Project/TheHive/blob/master/docker/thehive/docker-compose.yml) file creates an ElasticSearch container that is incompatible with the rest of the deployment.

### Steps to Reproduce
1. Pull/clone from `master`
1. cd to `./docker/thehive`
1. run `docker-compose up` in this directory
1. Wait for ElasticSearch-related errors to appear. 

### Possible Solutions
Potentially, reverting [this PR](https://github.com/TheHive-Project/TheHive/commit/2ef0838746cf5c8f8c3271c50e1d6d51f1eac121#r35452934) will remediate the issue. According to the docs, this project uses ElasticSearch5.0 for stateless storage. Despite this spec, the file was altered to have a major version bump.

Either way, the Docker file and documentation are out of sync.

### Complementary information

Sample error. One of many, but I'm cropping out any PII.
```
cortex_1         | [error] o.e.d.DBConfiguration - ElasticSearch request failure: POST:/cortex_4/_search?
cortex_1         | StringEntity({"query":{"match":{"relations":{"query":"user"}}},"size":0},Some(application/json))
cortex_1         |  => ElasticError(index_not_found_exception,no such index,Some(_na_),Some(cortex_4),None,List(ElasticError(index_not_found_exception,no such index,Some(_na_),Some(cortex_4),None,null,None)),None)
```

**Comment by milesflo** [comment]
Experimenting with this hypothesis now

**Comment by milesflo** [comment]
Reverting seems pretty fruitless

**Comment by arnydo** [comment]
It looks like Cortex 3.0.0 and TheHive 3.4.0 are "supposed" to be compatible with ES 6+.
But following those versions along with the migration guide (to know what the configuration is supposed to look like) I still get the errors on a fresh install.

https://blog.thehive-project.org/2019/09/11/thehive-3-4-0-cortex-3-0-0-released/
https://github.com/TheHive-Project/TheHiveDocs/blob/master/migration-guide.md

**Comment by arnydo** [comment]
I was able to get it running with the following compose file (Removed the RC tags and used the latest stable versions).
I did end up deleting the index for TheHive after spinning up because it kept failing. After deleting the index and restarting the container I got right in and was able to run the "update database" process.

```
version: "2"
services:
  elasticsearch:
    image: elasticsearch:6.8.0
    environment:
      - http.host=0.0.0.0
      - cluster.name=hive
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  cortex:
    image: thehiveproject/cortex:3.0.0
    ports:
      - "0.0.0.0:9001:9001"
  thehive:
    image: thehiveproject/thehive:3.4.0
    depends_on:
      - elasticsearch
      - cortex
   ports:
     - "0.0.0.0:9000:9000"
```
