### ISSUE TITLE
TheHive explodes in bright colors if you restart your browser after migrating the db

### ISSUE THREAD

**Issue by Trolldemorted** [TheHive-Project/TheHive#1205]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Moby Linux
| OS version (client)       | W10
| TheHive version / git hash   | [3.4.0](https://hub.docker.com/layers/thehiveproject/thehive/3.4.0/images/sha256-75174df50d772c76c360beb81b0b1225de8e4227c7b683b0bc73dab30b6ecc97)
| Package Type              | Docker

### Problem Description
If you reatart your browser after migrating the backend and frontend both constantly throw errors.

### Steps to Reproduce
- Take this docker-compose.yml:
```yaml
version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - script.allowed_types=inline
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  thehive:
    image: thehiveproject/thehive:3.4.0
    ports:
      - "0.0.0.0:9000:9000"
```
- Start the migration
- Restart your browser
- Navigate to localhost:9000
### Complementary information
Server output:
```
[...]
thehive_1        | [info] o.e.ErrorHandler - GET /api/user/current returned 404
thehive_1        | org.elastic4play.NotFoundError: user init not found
thehive_1        |      at org.elastic4play.database.DBGet.$anonfun$apply$2(DBGet.scala:37)
thehive_1        |      at scala.Option.fold(Option.scala:158)
thehive_1        |      at org.elastic4play.database.DBGet.$anonfun$apply$1(DBGet.scala:37)
thehive_1        |      at scala.util.Success.$anonfun$map$1(Try.scala:251)
thehive_1        |      at scala.util.Success.map(Try.scala:209)
thehive_1        |      at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
thehive_1        |      at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
thehive_1        |      at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
thehive_1        |      at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
thehive_1        |      at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
thehive_1        | [warn] p.a.m.DefaultJWTCookieDataCodec - decode: cookie has invalid signature! message = JWT signature does not match locally computed signature. JWT validity cannot be asserted and 
should not be trusted.
thehive_1        | [info] o.e.ErrorHandler - GET /api/user/current returned 404
thehive_1        | org.elastic4play.NotFoundError: user init not found
thehive_1        |      at org.elastic4play.database.DBGet.$anonfun$apply$2(DBGet.scala:37)
thehive_1        |      at scala.Option.fold(Option.scala:158)
thehive_1        |      at org.elastic4play.database.DBGet.$anonfun$apply$1(DBGet.scala:37)
thehive_1        |      at scala.util.Success.$anonfun$map$1(Try.scala:251)
thehive_1        |      at scala.util.Success.map(Try.scala:209)
thehive_1        |      at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
thehive_1        |      at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
thehive_1        |      at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
thehive_1        |      at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
thehive_1        |      at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
thehive_1        | [warn] p.a.m.DefaultJWTCookieDataCodec - decode: cookie has invalid signature! message = JWT signature does not match locally computed signature. JWT validity cannot be asserted and 
should not be trusted.
thehive_1        | [info] o.e.ErrorHandler - GET /api/user/current returned 404
thehive_1        | org.elastic4play.NotFoundError: user init not found
thehive_1        |      at org.elastic4play.database.DBGet.$anonfun$apply$2(DBGet.scala:37)
thehive_1        |      at scala.Option.fold(Option.scala:158)
thehive_1        |      at org.elastic4play.database.DBGet.$anonfun$apply$1(DBGet.scala:37)
thehive_1        |      at scala.util.Success.$anonfun$map$1(Try.scala:251)
thehive_1        |      at scala.util.Success.map(Try.scala:209)
thehive_1        |      at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
thehive_1        |      at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
thehive_1        |      at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
thehive_1        |      at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
thehive_1        |      at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[...]
```

Frontend:
![userinitnotfound](https://user-images.githubusercontent.com/10261186/72439314-fbfd4600-37a6-11ea-8659-6c66766a1320.png)
