### ISSUE TITLE
[Bug] Cortex "Organization > Configuration and Organization > Analyzers" Missing On GUI

### ISSUE THREAD

**Issue by BrunoMCBraga** [TheHive-Project/TheHive#1502]
### Request Type
Potential bug.

### Problem Description
I am currently trying to deploy TheHive with Docker image following: https://hub.docker.com/r/thehiveproject/thehive

However, when i access the GUI i see:
![Screenshot 2020-09-01 at 12 04 26](https://user-images.githubusercontent.com/5751467/91836594-4e627880-ec4b-11ea-893c-81b12db8f0a5.png)

instead of (source: https://github.com/TheHive-Project/CortexDocs/blob/master/admin/quick-start.md#step-7-optional-create-an-account-for-thehive-integration):

![image](https://user-images.githubusercontent.com/5751467/91836669-676b2980-ec4b-11ea-94c1-bc66221a7a1d.png)

I am not providing any configuration to the Hive. The docker compose file i am using is:

```
version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - script.inline=true
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /Users/brubraga/PycharmProjects/CTAMISPFeeder/Docker/thehivecontainer/es-db:/usr/share/elasticsearch/data
  cortex:
    image: thehiveproject/cortex:latest
    ports:
      - "0.0.0.0:9001:9001"
  thehive:
    image: thehiveproject/thehive:latest
    #volumes:
    #  - /Users/brubraga/PycharmProjects/CTAMISPFeeder/Docker/thehivecontainer/application.conf:/etc/thehive/application.conf
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
```

### Steps to Reproduce
1. Deploy Docker cluster using Docker compose above
