### ISSUE TITLE
Api Query _string not providing the correct results as of TH4

### ISSUE THREAD

**Issue by jeffrey-e** [TheHive-Project/TheHive#1786]
### Request Type
Bug

### Work Environment

```
version: '2'
services:
  cassandra:
    image: 'cassandra:3.11'
    container_name: cassandra
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - './cassandra/data:/var/lib/cassandra/data'
    mem_limit: 2GB
  thehive:
    image: 'thehiveproject/thehive4:4.0.3-1'
    container_name: thehive4
    restart: unless-stopped
    depends_on:
      - cassandra
    ports:
      - '0.0.0.0:9000:9000'
    volumes:
      - './thehive/application.conf:/etc/thehive/application.conf'
      - './thehive/data:/opt/data'
    command: '--no-config --no-config-secret'
    mem_limit: 1GB
  synapse:
    build: ./synapse
    image: lab/synapse:latest
    depends_on:
      - thehive
    mem_limit: 1GB
```

### Problem Description
When querying The Hive for cases it returns all cases instead of cases matching the string (used to be query string search back in the ES days)

### Possible solution
- Declare it deprecated and provide an alternative
- Adjust/Provide syntax to support new backend

### Steps to Reproduce
1. Perform a similar query as mentioned below
2. Analyse the results that matched for matches that should not be present

### Complementary information
```
http://localhost:9000/api/case/_search?range=all
{
  "query": {
    "_string": "nonexistent3254635y412"
  }
}
```

Results:
```
[
    {
        "_id": "~8424",
        "id": "~8424",
        "createdBy": "jeffrey@demo.nl",
        "updatedBy": "jeffrey@demo.nl",
        "createdAt": 1608241245572,
        "updatedAt": 1610395383559,
        "_type": "case",
        "caseId": 2,
        "title": "test2",
        "description": "test",
        "severity": 2,
        "startDate": 1608241200000,
        "endDate": null,
        "impactStatus": null,
        "resolutionStatus": null,
        "tags": [],
        "flag": false,
        "tlp": 2,
        "pap": 2,
        "status": "Open",
        "summary": null,
        "owner": "jeffrey@demo.nl",
        "customFields": {},
        "stats": {},
        "permissions": [
            "manageShare",
            "manageAnalyse",
            "manageTask",
            "manageCaseTemplate",
            "manageCase",
            "manageUser",
            "managePage",
            "manageObservable",
            "manageConfig",
            "manageAlert",
            "accessTheHiveFS",
            "manageAction"
        ]
    },
    {
        "_id": "~41072",
        "id": "~41072",
        "createdBy": "jeffrey@demo.nl",
        "updatedBy": "jeffrey@demo.nl",
        "createdAt": 1606387471163,
        "updatedAt": 1608241292600,
        "_type": "case",
        "caseId": 1,
        "title": "test",
        "description": "test",
        "severity": 2,
        "startDate": 1606387440000,
        "endDate": null,
        "impactStatus": null,
        "resolutionStatus": null,
        "tags": [],
        "flag": false,
        "tlp": 2,
        "pap": 2,
        "status": "Open",
        "summary": null,
        "owner": "jeffrey@demo.nl",
        "customFields": {
            "due-date": {
                "date": 1606407420000
            }
        },
        "stats": {},
        "permissions": [
            "manageShare",
            "manageAnalyse",
            "manageTask",
            "manageCaseTemplate",
            "manageCase",
            "manageUser",
            "managePage",
            "manageObservable",
            "manageConfig",
            "manageAlert",
            "accessTheHiveFS",
            "manageAction"
        ]
    },
    {
        "_id": "~40964232",
        "id": "~40964232",
        "createdBy": "jeffrey@demo.nl",
        "updatedBy": null,
        "createdAt": 1610395954499,
        "updatedAt": null,
        "_type": "case",
        "caseId": 3,
        "title": "test postman",
        "description": "*test1 \n\n test",
        "severity": 4,
        "startDate": 1610395953741,
        "endDate": null,
        "impactStatus": null,
        "resolutionStatus": null,
        "tags": [],
        "flag": false,
        "tlp": 2,
        "pap": 2,
        "status": "Open",
        "summary": null,
        "owner": "jeffrey@demo.nl",
        "customFields": {},
        "stats": {},
        "permissions": [
            "manageShare",
            "manageAnalyse",
            "manageTask",
            "manageCaseTemplate",
            "manageCase",
            "manageUser",
            "managePage",
            "manageObservable",
            "manageConfig",
            "manageAlert",
            "accessTheHiveFS",
            "manageAction"
        ]
    },
    {
        "_id": "~40964256",
        "id": "~40964256",
        "createdBy": "jeffrey@demo.nl",
        "updatedBy": "jeffrey@demo.nl",
        "createdAt": 1610457409190,
        "updatedAt": 1611786752754,
        "_type": "case",
        "caseId": 4,
        "title": "test postman",
        "description": "*test1 \n\n test",
        "severity": 4,
        "startDate": 1610457408781,
        "endDate": 1611786752667,
        "impactStatus": "NotApplicable",
        "resolutionStatus": "Indeterminate",
        "tags": [],
        "flag": false,
        "tlp": 2,
        "pap": 2,
        "status": "Resolved",
        "summary": "test",
        "owner": "jeffrey@demo.nl",
        "customFields": {},
        "stats": {},
        "permissions": [
            "manageShare",
            "manageAnalyse",
            "manageTask",
            "manageCaseTemplate",
            "manageCase",
            "manageUser",
            "managePage",
            "manageObservable",
            "manageConfig",
            "manageAlert",
            "accessTheHiveFS",
            "manageAction"
        ]
    }
]
```
