### ISSUE TITLE
TheHive 4.1 container fails to start

### ISSUE THREAD

**Issue by AC-WhiteGlint** [TheHive-Project/TheHive#1858]
Hi.

I tried to use the docker version of TheHive 4.1.0-1 but it cannot and give me this error : 

[warn] o.t.s.u.Retry [|] An error occurs (Could not instantiate implementation: org.janusgraph.diskstorage.lucene.LuceneIndex), retrying (9)

I tried a new deployment and an upgrade from 4.0.5-1 and this issue came back each time.

However no issue with the version 4.0.5-1

Please find my docker-compose

```
version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
  cortex:
    image: thehiveproject/cortex:3.1.1-1
    environment:
      - job_directory=/tmp/cortex-jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cortex-jobs:/tmp/cortex-jobs
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:10001:9001"
  thehive:
    image: thehiveproject/thehive4:4.1.0-1
    depends_on:
      - cortex
    ports:
      - "0.0.0.0:10000:9000"
    command: --cortex-port 9001
volumes:
  esdata:
```
