### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ryukam** [TheHive-Project/TheHive#2035]
### Request Type

Question

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu|
| OS version (client)        | Ubuntu|
| Virtualized  Env.          | True|
| Dedicated RAM              | 8 GB                                 |
| vCPU                       | 4|
| TheHive version /4.1.4-1|
| Package Type               | Docker , Binary, From source |
| Database                   | Cassandra|
| Index type                 | Lucene|
| Attachments storage        | Local, NFS|
| Browser type & version     | Chrome 90.0.4430.212|

### Question
Hi all,

We are trying to raise an alert form elastalert to the thive by including an IP observable.

The alert it raised in the hive, we see that an IP observable is added to the alert but unfortunatly there is no data inside the observable.

Below our simple rule on Elastalert :
```
name: win_admin_rdp_login
index: "winlogbeat-*"
use_strftime_index: true
type: any
filter:
  - query:
      query_string:
        query: "(winlog.channel:Security AND winlog.event_id:4624 AND winlog.event_data.LogonType:10  AND winlog.event_data.AuthenticationPackageName:/[Nn][Ee][Gg][Oo][Tt][Ii][Aa][Tt][Ee]/  AND winlog.event_data.TargetUserName:/[Aa][Dd][Mm][Ii][Nn].*/)"
alert:
  - "hivealerter"
hive_connection:
  hive_host: https://thehive
  hive_port: 443
  hive_apikey: 
  hive_verify: false
  hive_proxies:
    http: ''
    https: ''
hive_observable_data_mapping:
    - ip: "{match[source][ip]}"
hive_alert_config:
  title: "title"
  type: "our first alert config type"
  source: "our first alert elastalert"
  description: "123"
  severity: 2
  tlp: 2
  status: "Waiting"
  follow: true
```
Could you help us on this issue please.
