### ISSUE TITLE
[Bug] Webhook triggered by LogInMyTask return Scala error Predicate not found

### ISSUE THREAD

**Issue by razieldrake** [TheHive-Project/TheHive#2124]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian 5.10.13-1kali1  |
| OS version (client)        | Debian 5.10.13-1kali1    |
| Virtualized  Env.          | True                                 |
| Dedicated RAM              | 16GB                                 |
| vCPU                       | 8                       |
| TheHive version / git hash | 4.1.x             |
| Package Type               | Docker |
| Database                   | Cassandra                |
| Index type                 |  Elasticsearch                |
| Attachments storage        | Local                 |

### Problem Description
Through docker-compose (for testing, it is the same behaviour on local install), i'm trying to create a webhook triggered by the LogInMyTask trigger. (You can find trigger/event in https://github.com/TheHive-Project/TheHive/tree/7575943129324e8d7aad9253030fdba05c00ecf7/thehive/app/org/thp/thehive/services/notification/triggers as they are pretty hard to find).

Here's the configuration of the webhook in the application.conf:

```conf
notification.webhook.endpoints = [
  {
    name: local
    url: "http://172.17.0.1:8000/webhook"
    version: 0
    wsConfig: {}
    auth: 
    {
      type: "none"
    }
    includedTheHiveOrganisations: ["*"]
    excludedTheHiveOrganisations: []
  }
]
```

Here's the curl command used for registering webhook:

```bash
curl -X PUT -u $thehive_user:$thehive_password -H 'Content-type: application/json' $thehive_url/api/config/organisation/notification -d '{"value":[{"delegate":false,"trigger":{"name":"LogInMyTask"},"notifier":{"name":"webhook","endpoint":"local"}}]} '
```
It is working fine with the "AnyEvent" trigger, but with the LogInMyTask trigger TheHive returns:

```log
[error] o.t.t.s.n.NotificationActor [|6871e5ba] Execution of notification NotificationConfig(false,Configuration(Config(SimpleConfigObject({"name":"LogInMyTask"}))),Configuration(Config(SimpleConfigObject({"endpoint":"local","name":"webhook"}))),Set()) has failed for user None / CERT
thehive4         | java.util.NoSuchElementException: Predicate does not hold for Trigger(LogInMyTask)
thehive4         | 	at scala.util.Success.filter(Try.scala:263)
thehive4         | 	at scala.util.Try$WithFilter.flatMap(Try.scala:142)
thehive4         | 	at org.thp.thehive.services.notification.NotificationActor.$anonfun$executeNotification$1(NotificationActor.scala:127)
thehive4         | 	at scala.collection.Iterator.foreach(Iterator.scala:943)
thehive4         | 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
thehive4         | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
thehive4         | 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
thehive4         | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
thehive4         | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)

```
Following the compose file i'm using:

```yml
version: '3.8'
services:
  elasticsearch:
    image: 'elasticsearch:7.11.1'
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - '0.0.0.0:9200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - './data:/usr/share/elasticsearch/data'
      - './logs:/usr/share/elasticsearch/logs'
  cortex:
    image: 'thehiveproject/cortex:latest'
    container_name: cortex
    restart: unless-stopped
    command:
      --no-config
      --job-directory ${JOB_DIRECTORY}
    environment:
      - 'JOB_DIRECTORY=jobs/'
    volumes:
      - './cortex/application.conf:/etc/cortex/application.conf'
      - './jobs:/opt/cortex/jobs/'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./responders:/opt/cortex/analyzers/responders
    depends_on:
      - elasticsearch
    ports:
      - '0.0.0.0:9001:9001'
  thehive:
    image: 'thehiveproject/thehive4:latest'
    container_name: thehive4
    restart: unless-stopped
    ports:
      - '0.0.0.0:9000:9000'
    volumes:
      - ./application.conf:/etc/thehive/application.conf
      - ./db:/opt/thp/thehive/db
      - ./index:/opt/thp/thehive/index
      - ./data:/opt/thp/thehive/data
    command: '--no-config --no-config-secret'

```

The behaviour is similar on local install.

### Steps to Reproduce
1. Build your theHive (Install,Create organisaiton, Create user org_admin,customize application.conf...)
2. Register the webhook with the following curl command replacing variables name by your own values (reminder: the user have to be org_admin): 
```bash
curl -X PUT -u $thehive_user:$thehive_password -H 'Content-type: application/json' $thehive_url/api/config/organisation/notification -d '{"value":[{"delegate":false,"trigger":{"name":"LogInMyTask"},"notifier":{"name":"webhook","endpoint":"local"}}]} '
```
3. Start your endpoint for your webhook to be handled (i'm using Hug exposed on port 8000)

### Possible Solutions

Several weeks ago it did manage to achieve to make the webhook works. After that i have added Cortex to the compose file, and update theHive version. Since then it doesn't seem to work anymore. I was hoping that it will work if i use 4.1.6, but it doesn't to work either. So i have no more clue about it. 

Thanks in advance for your solutions/advices
