### ISSUE TITLE
[Doc missing info] Missing logback.xml causing TheHive service to fail the start

### ISSUE THREAD

**Issue by D3vil0p3r** [TheHive-Project/TheHive#2463]
### Request Type
I'm setting TheHive on Arch Linux.

By following the official documentation https://docs.thehive-project.org/thehive/installation-and-configuration/installation/step-by-step-guide , at the end TheHive fails to start with 255/exception.

This issue has been solved by running:
```
sudo cp /opt/thehive/conf/logback.xml /etc/thehive/
sudo chgrp thehive /etc/thehive/logback.xml
sudo chmod 640 /etc/thehive/logback.xml
```
Also the permission to give to `thehive` user or group for writing `/var/log/thehive` folder for writing `application.log` is missing on that doc.

The command `wget https://github.com/TheHive-Project/TheHive/blob/master/package/thehive.service` in that doc does not give in output the corrent .service content file.

Furthermore, on the `application.conf` shown in that step-by-step guide should contain the `include "/etc/thehive/secret.conf"` otherwise `thehive.service` fails to start.

On the part of the document with `cassandra.yaml` the seeds addresses should contain the port, so they should be like:
```yaml
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          # Ex: "<ip1:port1>,<ip2:port2>,<ip3:port3>"
          - seeds: 'xx.xx.xx.xx:yyyy' # self for the first node
```

These three commands are missing on the guide step-by-step docs. Please update it with this information.
