### ISSUE TITLE
The hive docker image has no latest tag

### ISSUE THREAD

**Issue by Xumeiquer** [TheHive-Project/TheHive#670]
### Problem Description
The Docker image for The Hive (thehiveproject/thehive) has no latest tag

### Possible Solutions
Tag the latest image and upload the image.

**Comment by gonrada** [comment]
docker pull -a thehiveproject/thehive
thehiveproject/thehive                          3.1.0-0.1RC1        6293fa1d75b8        2 weeks ago         861MB

There isn't any docker file with the latest tag, but perhaps this might help.

**Comment by RANGERBEE** [comment]
edited the "thehive" service in docker-compose file:
```
  thehive:
    image: thehiveproject/thehive:3.1.0-0.1RC1
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
```

thanks @gonrada
