### ISSUE TITLE
LDAP authentication failing after upgrading to 3.1.0-0-RC2

### ISSUE THREAD

**Issue by christophetd** [TheHive-Project/TheHive#703]
# LDAP authentication failing after upgrading to 3.1.0-0-RC2

### Request Type

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Ubuntu
| TheHive version / git hash   | 3.1.0-0.1RC1
| Package Type              | Docker

docker-compose : 

```yaml
version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - path.repo=/data/backup/
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - script.inline=true
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    volumes:
      - /home/hk/the_hive/data/es/:/usr/share/elasticsearch/data/
      - /home/hk/the_hive/data/backup/:/data/backup/
  cortex:
    image: certbdf/cortex:latest
    ports:
      - "10.0.2.21:9001:9001"
    volumes:
      - /home/user/the_hive/Cortex-Analyzers/analyzers:/opt/Cortex-Analyzers/analyzers:ro
      - /home/user/the_hive/cortex/application.conf:/etc/cortex/application.conf:ro
  thehive:
    image: thehiveproject/thehive:3.1.0-0.1RC2
    volumes:
      - /home/user/the_hive/application_hive_3.2.conf:/etc/thehive/application.conf
      - /home/user/certs/:/var/certs/
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "10.0.x.x:9000:9000"
      - "10.0.x.x:9443:9443"
```

application_hive_3.2.conf : 

```conf
auth.provider = [local,ldap]
auth.type = [local,ldap]
auth.ldap.serverName = "10.0.x.x:389"
auth.ldap.useSSL = false
auth.ldap.bindDN = "uid=ldap_browser,dc=xxx,dc=ch"
auth.ldap.bindPW = "xxx"
auth.ldap.baseDN = "dc=xxx,dc=xx"
auth.ldap.filter = "(&(objectClass=inetOrgPerson)(uid={0}))"

# Maximum time between two requests without requesting authentication
session {
  warning = 5m
  inactivity = 2h
}

https.port: 9443
play.server.https.keyStore.path: "/var/certs/hive.jks"
play.server.https.keyStore.type: "JKS"
play.server.https.keyStore.password: "xxx"
play.server.https.trustStore.path: "/var/certs/hive.jks"
play.server.https.trustStore.type: "JKS"
play.server.https.trustStore.password: "xxx"


cortex {
  "CORTEX-SERVER-ID" {
    url = "http://10.0.x.x:9001"
    key = "xxx"
  }
}

```

### Problem Description

I previously opened [an issue](https://github.com/TheHive-Project/TheHive/issues/674) when upgrading from 3.0.9 to 3.1.0-0-RC1. The bug has been fixed in the RC2, but I'm having an issue regarding LDAP authentication.

Once I restart Hive with the new version and I try to login on the web UI just like before, I get the exceptions:

```
thehive_1        | [error] o.e.s.a.MultiAuthSrv - Authentication failure
thehive_1        | org.elastic4play.AuthenticationError: Authentication using API key is not supported
thehive_1        |      at org.elastic4play.services.AuthSrv.authenticate(UserSrv.scala:44)
thehive_1        |      at org.elastic4play.services.AuthSrv.authenticate$(UserSrv.scala:44)
thehive_1        |      at org.elastic4play.services.auth.LdapAuthSrv.authenticate(LdapAuthSrv.scala:110)
thehive_1        |      at org.elastic4play.services.auth.MultiAuthSrv.$anonfun$authenticate$2(MultiAuthSrv.scala:62)
thehive_1        |      at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:46)
thehive_1        |      at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:44)
thehive_1        |      at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
thehive_1        |      at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
thehive_1        |      at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
thehive_1        |      at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)


thehive_1        | [error] o.e.s.a.MultiAuthSrv - Authentication failure
thehive_1        | org.elastic4play.AuthenticationError: Authentication using API key is not supported
thehive_1        |      at org.elastic4play.services.AuthSrv.authenticate(UserSrv.scala:44)
thehive_1        |      at org.elastic4play.services.AuthSrv.authenticate$(UserSrv.scala:44)
thehive_1        |      at org.elastic4play.services.auth.LdapAuthSrv.authenticate(LdapAuthSrv.scala:110)
thehive_1        |      at org.elastic4play.services.auth.MultiAuthSrv.$anonfun$authenticate$2(MultiAuthSrv.scala:62)
thehive_1        |      at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:46)
thehive_1        |      at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$$nestedInanonfun$forAllAuthProvider$1$1.applyOrElse(MultiAuthSrv.scala:44)
thehive_1        |      at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
thehive_1        |      at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
thehive_1        |      at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
thehive_1        |      at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)


thehive_1        | [error] o.e.s.a.LdapAuthSrv - LDAP authentication failure
thehive_1        | org.elastic4play.AuthenticationError: User not found in LDAP server
thehive_1        |      at org.elastic4play.services.auth.LdapConnection.$anonfun$getUserDN$1(LdapAuthSrv.scala:69)
thehive_1        |      at scala.util.Try$.apply(Try.scala:209)
thehive_1        |      at org.elastic4play.services.auth.LdapConnection.getUserDN(LdapAuthSrv.scala:63)
thehive_1        |      at org.elastic4play.services.auth.LdapConnection.$anonfun$authenticate$1(LdapAuthSrv.scala:75)
thehive_1        |      at org.elastic4play.services.auth.LdapConnection.$anonfun$connect$2(LdapAuthSrv.scala:49)
thehive_1        |      at scala.util.Try$.apply(Try.scala:209)
thehive_1        |      at org.elastic4play.services.auth.LdapConnection.$anonfun$connect$1(LdapAuthSrv.scala:47)
thehive_1        |      at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
thehive_1        |      at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
thehive_1        |      at scala.collection.immutable.List.foldLeft(List.scala:86)
```
