### ISSUE TITLE
no module - cortexutils

### ISSUE THREAD

**Issue by RANGERBEE** [TheHive-Project/TheHive#807]
### Request Type

![image](https://user-images.githubusercontent.com/15255470/49175487-9bac0a80-f340-11e8-85b2-80c3af8dafb8.png)

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 3.x
| Package Type              | Docker

![image](https://user-images.githubusercontent.com/15255470/49175556-bda58d00-f340-11e8-9c20-07efaf710702.png)

### Problem Description
Analyzers failing. Not sure why as they are all configured and reachable. the errors displayed in log report "raw" states no cortexutils found.  How can this be if all built from latest git pull and docker build??

### Steps to Reproduce
Build off current master branch, have docker build stack..

### Complementary information
Completely lost here. Help much appreciated...   modules not loading in python scripts, why?

**Comment by RANGERBEE** [comment]
disregard the MISP error as I fixed it by deselecting check of certs..    Thanks..

**Comment by crackytsi** [comment]
cortexutils is a python library.
you need to install it seperately
e.g. 
```
pip2 install cortexutils
pip3 install cortexutils
```

**Comment by crackytsi** [comment]
Note that most of the Analyzers or Responders need some additional modules
Official guide says:

```
cd path/to/Cortex-Analyzers
git pull
for I in analyzers/*/requirements.txt; do sudo -H pip2 install -U -r $I || true; done && \
for I in analyzers/*/requirements.txt; do sudo -H pip3 install -U -r $I || true; done
```

**Comment by nadouani** [comment]
Thanks @crackytsi for the support!

**Comment by nadouani** [comment]
@RANGERBEE Please make sure to ask the question in the right place. This is a Cortex related question, you should not ask it on TheHive's repo.

**Comment by RANGERBEE** [comment]
thanks guys!!

**Comment by RANGERBEE** [comment]
To comfirm, I need to install the module in the TheHives docker container build?  So how do we edit the docker build file???

**Comment by nadouani** [comment]
Non , this must be available in the container that contains the Cortex analyzers

**Comment by RANGERBEE** [comment]
got it, so I need to create an entrypoint file for the cortex container to run a check and install of requirements....

**Comment by nadouani** [comment]
Well, do you have the latest docker image of cortex? you got it from which docker repo? it should already contain all the required libraries

**Comment by RANGERBEE** [comment]
Here is my docker compose file with a little edits - from lates "master" TheHive git-Repo.

Really appreciate the help - a little lost in the sauce here.  ;-)

```yaml
version: "2"
services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    # volumes:
    #  - /etc/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - script.inline=true
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "0.0.0.0:9300:9300"
      - "0.0.0.0:9200:9200"

  cortex:
    restart: always
    image: thehiveproject/cortex:latest
    # volumes:
    #  - /opt/c_docker_hive/conf/application.conf:/etc/thehive/application.conf
    # - /opt/c_docker_hive/cortex/Cortex-Analyzers/analyzers:/opt/Cortex-Analyzers/analyzers
    # - /opt/c_docker_hive/cortex/Cortex-Analyzers/responders:/opt/Cortex-Analyzers/responders
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
    
  thehive:
    restart: always
    image: thehiveproject/thehive:3.1.0-0.1RC3
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
      ## Specify your cortex API key to a user part of the CORTEX Org that controls the analyzers
    command: --cortex-port 9001 --cortex-key fMNSMrVY9J2SQjE4v8Ek0B226/v7ax1T
```
